import os
import math as M
import datetime as DT 
from netCDF4 import *
import pyDart
import ens 
import glob
from optparse import OptionParser
from nc_prior_file import *
from ens import calcHx

import json
import pandas as pd
import pickle
import numpy as np
import cftime
import state_vector as state_vector
import datetime as dt
import json
import xarray as xr

day_utime   = "days since 1601-01-01 00:00:00"
sec_utime   = "seconds since 1970-01-01 00:00:00"


if __name__ == "__main__":

    print("\n \n <<<<<======================================================================>>>>>> \n \n")
    print("     EXPERIMENT CALCULATIONS!       \n\n ")

    usage = "usage: %prog [options] arg"
    parser = OptionParser(usage)

    parser.add_option("-e",  "--exp",    dest="exp",      default=None, type="string", help = "Path to the json experiment file generated by run")

    (options, args) = parser.parse_args()

    if options.exp:
        with open(options.exp, 'rb') as f:
            exper = json.load(f)


    ## step 1 = calculate posterior files just like the prior files

    obs_file = exper['radar_obs']
    window = int(exper['DA_PARAMS']['assim_window'])
    obs_error = exper['DA_PARAMS']['obs_errors']
    outlier = exper['DA_PARAMS']['outlier']
    obs_include = exper['DA_PARAMS']['obs_included']
    path = exper['base_path']
    start = DT.datetime.strptime(exper['DA_PARAMS']['DA_start_time'], '%Y-%m-%d %H:%M:%S')
    end   = DT.datetime.strptime(exper['DA_PARAMS']['DA_end_time'], '%Y-%m-%d %H:%M:%S')
    tdel  = DT.timedelta(seconds=exper['DA_PARAMS']['assim_freq'])
    
    ob_f = pd.read_csv(obs_file)
    
    for analysis_time in np.arange(start, end+tdel, tdel):
        #analysis_time.astype(DT.timedelta)
        analysis_time = pd.Timestamp(analysis_time)
    
        lat     = np.empty((0))
        lon     = np.empty((0))
        dates   = np.empty((0))
        value   = np.empty((0))
        kind    = np.empty((0))
        height  = np.empty((0))
        elev    = np.empty((0))
        az      = np.empty((0))
        err_var = np.empty((0))
        idx     = np.empty((0))
    
        
        
        print("\n --> ComputeHx:  Reading in model state for HxF at %s \n" %  (analysis_time.strftime("%Y-%m-%d %H:%M:%S")))
        
        # read from history files
          
            
        files, myDT = ens.FindRestartFiles(exper, analysis_time, ret_exp=False)
        
        state = ens.read_CM1_ens(files, exper, state_vector=state_vector.Hxf, DateTime=myDT)   
        ens.ens_CM1_C2A(state)
        ens.ens_CM1_coords(state)
        
          
        Hxfm = np.empty((0,state.ne))  # need to init this here cause need size of ensemble
        
        
        # if you want only a subset of observations, this will do that. Make sure to add additional options as the file contains more data
        if len(obs_include) > 0:
            include = []
            for ob in obs_include:
                print(f'-------->> INCLDUING OBSERVATION TYPE {ob}')
                if ob == "DBZ0_W":
                    include.append(14)
                    ob_f.loc[ob_f.kind==13, 'kind'] = 14 # recode all clear air obs to be vertical velocity         
                if ob == "DBZ0":
                    include.append(13)
                if ob == "DBZ":
                    include.append(12)
                if ob == 'VR':
                    include.append(11)
        
            ob_f = ob_f[ob_f['kind'].isin(include)]
        
        #set spatial and temporal conditions to index the observation data 
        g_lat_max = state.late[:].max()
        g_lat_min = state.late[:].min()
        g_lon_max = state.lone[:].max()
        g_lon_min = state.lone[:].min()
        g_alt_max = max(state.zc.data[:]) + state.hgt
        g_alt_min = min(state.zc.data[:]) + state.hgt
        
        dt     = DT.timedelta(0,int(window/2))
        begin  = cftime.date2num(analysis_time - dt, sec_utime)
        ending = cftime.date2num(analysis_time + dt, sec_utime)
        
        data_mask = (ob_f.utime >= begin) & (ob_f.utime <= ending) & \
                  (ob_f.lat <= g_lat_max) & (ob_f.lat >= g_lat_min) & \
                  (ob_f.lon <= g_lon_max) & (ob_f.lon >= g_lon_min)
        
        subdata = ob_f[data_mask]
        
        if len(subdata.index) > 0:
            print("\n --> ComputeHx:  Total number of obs found at search time: %s \n" % len(subdata.index))
        else:
            print("\n --> ComputeHx:  No obs found at search time:  %s exiting......\n" % (analysis_time))
            sys.exit(0)
        
        
        #### IF DOING NORMAL EXPERIMENT, USE THIS
        idx, Hxf, kind, lat, lon, height, elev, azimuth = ens.calcHx(state, subdata['kind'].values,subdata['lat'].values,                                         
                                                                 subdata['lon'].values,subdata['height'].values,
                                                                   subdata['elevation'].values,subdata['azimuth'].values)
        
        nobs = np.size(idx) 
        
        print("\n --> ComputeHx:  Total number of obs found is: %d \n" % (nobs))
        
          #### IF DOING NORMAL EXPERIMENT, USE THIS
        err_var = np.append(err_var, subdata['error_var'].values[idx])   
        value   = np.append(value,   subdata['value'].values[idx])
        dates   = np.append(dates,   subdata['date'].values[idx])
            
        # Overide the file observation std deviations with either defaults at top of script or input parameters
        
        for key in obs_error.keys():
            print_once = True
            for n, item in enumerate(kind):
                if int(item) == int(key):
                    err_var[n] = obs_error[key][1]**2.0
                if print_once:
                    print("\n --> ComputeHx:  Changing %s observational error to:  %s" % (obs_error[key][0],obs_error[key][1]))
                    print_once = False
        
        # Here we choose to create a coordinate system of x/y's based from the SW corner (lat,lon) of model grid.
        # The observations' new x/y's are then in the model's coordinate system relative to reference (lat,lon) of grid
        
        xs, ys = pyDart.dll_2_dxy(state.late[0], lat, state.lone[0], lon, degrees=True)
        zs     = height
        
        Hxfbar = np.average(Hxf,axis=1)
        
        # We dont use this flag (is supposed to be a flag to tell one whether the obs is used for verification or assimilation, or thrown out)
        status = np.ones(nobs)
        
        # Compute standard deviation of model priors versus observation
        outlier = np.abs(Hxfbar-value)/np.sqrt(Hxf.var(ddof=1,axis=1)+err_var)
        
        create_prior_file(state.ne, path)
        write_prior(state.ne, kind, value, dates, err_var, xs, ys, zs, Hxf, Hxfbar, lat, lon, elev, azimuth, status, outlier, path)
        newPriorFile = os.path.join(path, "Posterior_%s.nc" % analysis_time.strftime("%Y-%m-%d_%H:%M:%S"))
        os.rename(os.path.join(path, "Prior.nc"), newPriorFile)
        print('FINISHED MAKING FILE!!!')


    ## step 2: combine all the needed files together

    print("COMBINING FILES")

    file_version = 'Prior' 
    dirname = os.path.join(path,file_version+'*.nc')
    file_list = sorted(glob.glob(dirname),key=os.path.getmtime)
    
    num2obs = {11: ["VR"], 12:["DBZ"], 13:['DBZ0'], 14:['DBZ0_W']}
    obs2num  = {'VR':11, 'DBZ':12, 'DBZ0':13, 'DBZ0_W':14}
    
    obs = exper['DA_PARAMS']['obs_included']
    obnum = [obs2num[ob] for ob in obs]
    
    ensN = exper['ne']
    t    = len(file_list)
    n = np.max([len(xr.open_dataset(file).ob_num) for file in file_list])
    times = [DT.datetime.strptime(os.path.basename(file).replace(file_version, ''), '_%Y-%m-%d_%H:%M:%S.nc') for file in file_list]
    
    
    # step one - make the skeleton of dataset
    coords = { 't': np.arange(0, t),'ne': np.arange(0,ensN),'n':  np.arange(0, n)}
    myds = xr.Dataset( coords)
    #print(myds.keys())
    
    
    # fill with nan variables of proper size
    f = xr.open_dataset(file_list[0])
    for v in list(f.keys()):
        if v not in ['type', 'dates']:
            if len(np.shape(f[v])) == 1:
                myds[v] = (('t', 'n'), np.zeros([t, n])*np.nan)
            if len(np.shape(f[v])) == 2:
                myds[v] = (('t', 'n', 'ne'), np.zeros([t, n, ensN])*np.nan)
    f.close()
                
    # fill nan variables with actual data
    for fi, file in enumerate(file_list):
        f = xr.open_dataset(file)
        fn = len(f.ob_num)
        for v in list(myds.keys()):
            myds[v][fi, :fn] = f[v].values
        f.close()
    
    # add time var
    myds['time'] =  (('t'), times) 
    
    # add masks for different variables
    for ob in obs:
        myds[ob] = (('t', 'n'), myds['kind'].values == obs2num[ob])
    
    
    ##### now add in the posterior values!!
    myds['Hxf_post']= (('t', 'n', 'ne'), np.zeros([t, n, ensN])*np.nan)
    myds['Hxfbar_post']= (('t', 'n'), np.zeros([t, n])*np.nan)
    myds['outlier_post']= (('t', 'n'), np.zeros([t, n])*np.nan)
    
    file_version='Posterior'
    dirname = os.path.join(path,file_version+'*.nc')
    file_list = sorted(glob.glob(dirname),key=os.path.getmtime)
    for fi, file in enumerate(file_list):
        f = xr.open_dataset(file)
        fn = len(f.ob_num)
        #for v in list(myds.keys()):
        myds['Hxf_post'][fi, :fn] = f['Hxf'].values
        myds['Hxfbar_post'][fi, :fn] = f['Hxfbar'].values
        myds['outlier_post'][fi, :fn] = f['outlier'].values
        f.close()
    
    savename = os.path.join(os.path.dirname(file_list[0]), f'AllPrior_Post.nc')
    myds.to_netcdf(savename, format='NETCDF4')

            