import os
import math as M
import datetime as DT 
from netCDF4 import *
import pyDart
import ens 
import glob
from optparse import OptionParser
from nc_prior_file import *
from ens import calcHx

import json
import pandas as pd
import pickle
import numpy as np
import cftime
import state_vector as state_vector
import datetime as dt
import json
import xarray as xr

def findnearest(array, value):
    array = np.asarray(array)
    return (np.abs(array-value)).argmin()

day_utime   = "days since 1601-01-01 00:00:00"
sec_utime   = "seconds since 1970-01-01 00:00:00"


if __name__ == "__main__":

    print("\n \n <<<<<======================================================================>>>>>> \n \n")
    print("     EXPERIMENT CALCULATIONS!       \n\n ")

    usage = "usage: %prog [options] arg"
    parser = OptionParser(usage)

    parser.add_option("-e",  "--exp",    dest="exp",    default=None,  type="string", help = "Path to the json experiment file generated by run")
    parser.add_option("-s",  "--stats",  dest='stats',  default=False, action="store_true", help = "if True, runs forward operator on posterior files as well and saves all Prior and Posterior files into AllPrior_Post.nc")
    parser.add_option("-f",  "--fcst",  dest="fcst",    default=False, action="store_true", help = "if True, merges all the forecast files into one file called full_ens_fcst.nc")
    parser.add_option(  "--fcst_file",  dest="fcst_file",    default=False, action="store_true", help = "if True, uses code for the forecast experiment file")
    parser.add_option("-w",  "--wtg",    dest="wtg",    default=False, action="store_true", help = "if True, calculates weak thermal gradient residual for the full ensemble and puts it in WTG.nc")

    (options, args) = parser.parse_args()

    if options.exp:
        with open(options.exp, 'rb') as f:
            exper = json.load(f)
    
    path = exper['base_path']
    


    if options.stats:
        print('PRODUCING POSTERIOR FILES')

        obs_file = exper['radar_obs']
        window = int(exper['DA_PARAMS']['assim_window'])
        obs_error = exper['DA_PARAMS']['obs_errors']
        outlier = exper['DA_PARAMS']['outlier']
        obs_include = exper['DA_PARAMS']['obs_included']
    
        start = DT.datetime.strptime(exper['DA_PARAMS']['DA_start_time'], '%Y-%m-%d %H:%M:%S')
        end   = DT.datetime.strptime(exper['DA_PARAMS']['DA_end_time'], '%Y-%m-%d %H:%M:%S')
        tdel  = DT.timedelta(seconds=exper['DA_PARAMS']['assim_freq'])


        ## step 1 = calculate posterior files just like the prior files
        ob_f = pd.read_csv(obs_file)
        
        for analysis_time in np.arange(start, end+tdel, tdel):
            #analysis_time.astype(DT.timedelta)
            analysis_time = pd.Timestamp(analysis_time)
        
            lat     = np.empty((0))
            lon     = np.empty((0))
            dates   = np.empty((0))
            value   = np.empty((0))
            kind    = np.empty((0))
            height  = np.empty((0))
            elev    = np.empty((0))
            az      = np.empty((0))
            err_var = np.empty((0))
            idx     = np.empty((0))
            
            print("\n --> ComputeHx:  Reading in model state for HxF at %s \n" %  (analysis_time.strftime("%Y-%m-%d %H:%M:%S")))
            
            # read from history files
            files, myDT = ens.FindRestartFiles(exper, analysis_time, ret_exp=False)
            
            state = ens.read_CM1_ens(files, exper, state_vector=state_vector.Hxf, DateTime=myDT)   
            ens.ens_CM1_C2A(state)
            ens.ens_CM1_coords(state)
              
            Hxfm = np.empty((0,state.ne))  # need to init this here cause need size of ensemble
            
            # if you want only a subset of observations, this will do that. Make sure to add additional options as the file contains more data
            if len(obs_include) > 0:
                include = []
                for ob in obs_include:
                    print(f'-------->> INCLDUING OBSERVATION TYPE {ob}')
                    if ob == "DBZ0_W":
                        include.append(14)
                        ob_f.loc[ob_f.kind==13, 'kind'] = 14 # recode all clear air obs to be vertical velocity         
                    if ob == "DBZ0":
                        include.append(13)
                    if ob == "DBZ":
                        include.append(12)
                    if ob == 'VR':
                        include.append(11)
            
                ob_f = ob_f[ob_f['kind'].isin(include)]
            
            #set spatial and temporal conditions to index the observation data 
            g_lat_max = state.late[:].max()
            g_lat_min = state.late[:].min()
            g_lon_max = state.lone[:].max()
            g_lon_min = state.lone[:].min()
            g_alt_max = max(state.zc.data[:]) + state.hgt
            g_alt_min = min(state.zc.data[:]) + state.hgt
            
            dt     = DT.timedelta(0,int(window/2))
            begin  = cftime.date2num(analysis_time - dt, sec_utime)
            ending = cftime.date2num(analysis_time + dt, sec_utime)
            
            data_mask = (ob_f.utime >= begin) & (ob_f.utime <= ending) & \
                      (ob_f.lat <= g_lat_max) & (ob_f.lat >= g_lat_min) & \
                      (ob_f.lon <= g_lon_max) & (ob_f.lon >= g_lon_min)
            
            subdata = ob_f[data_mask]
            
            if len(subdata.index) > 0:
                print("\n --> ComputeHx:  Total number of obs found at search time: %s \n" % len(subdata.index))
            else:
                print("\n --> ComputeHx:  No obs found at search time:  %s exiting......\n" % (analysis_time))
                sys.exit(0)
            
            
            #### IF DOING NORMAL EXPERIMENT, USE THIS
            idx, Hxf, kind, lat, lon, height, elev, azimuth = ens.calcHx(state, subdata['kind'].values,subdata['lat'].values,                                         
                                                                     subdata['lon'].values,subdata['height'].values,
                                                                       subdata['elevation'].values,subdata['azimuth'].values)
            
            nobs = np.size(idx) 
            
            print("\n --> ComputeHx:  Total number of obs found is: %d \n" % (nobs))
            
              #### IF DOING NORMAL EXPERIMENT, USE THIS
            err_var = np.append(err_var, subdata['error_var'].values[idx])   
            value   = np.append(value,   subdata['value'].values[idx])
            dates   = np.append(dates,   subdata['date'].values[idx])
                
            # Overide the file observation std deviations with either defaults at top of script or input parameters
            
            for key in obs_error.keys():
                print_once = True
                for n, item in enumerate(kind):
                    if int(item) == int(key):
                        err_var[n] = obs_error[key][1]**2.0
                    if print_once:
                        print("\n --> ComputeHx:  Changing %s observational error to:  %s" % (obs_error[key][0],obs_error[key][1]))
                        print_once = False
            
            # Here we choose to create a coordinate system of x/y's based from the SW corner (lat,lon) of model grid.
            # The observations' new x/y's are then in the model's coordinate system relative to reference (lat,lon) of grid
            
            xs, ys = pyDart.dll_2_dxy(state.late[0], lat, state.lone[0], lon, degrees=True)
            zs     = height
            
            Hxfbar = np.average(Hxf,axis=1)
            
            # We dont use this flag (is supposed to be a flag to tell one whether the obs is used for verification or assimilation, or thrown out)
            status = np.ones(nobs)
            
            # Compute standard deviation of model priors versus observation
            outlier = np.abs(Hxfbar-value)/np.sqrt(Hxf.var(ddof=1,axis=1)+err_var)
            
            create_prior_file(state.ne, path)
            write_prior(state.ne, kind, value, dates, err_var, xs, ys, zs, Hxf, Hxfbar, lat, lon, elev, azimuth, status, outlier, path)
            newPriorFile = os.path.join(path, "Posterior_%s.nc" % analysis_time.strftime("%Y-%m-%d_%H:%M:%S"))
            os.rename(os.path.join(path, "Prior.nc"), newPriorFile)
            print('FINISHED MAKING FILE!!!')
    
    
        ## step 2: combine all the needed files together
    
        print("COMBINING FILES")
    
        file_version = 'Prior' 
        dirname = os.path.join(path,file_version+'*.nc')
        file_list = sorted(glob.glob(dirname),key=os.path.getmtime)
        
        num2obs = {11: ["VR"], 12:["DBZ"], 13:['DBZ0'], 14:['DBZ0_W']}
        obs2num  = {'VR':11, 'DBZ':12, 'DBZ0':13, 'DBZ0_W':14}
        
        obs = exper['DA_PARAMS']['obs_included']
        obnum = [obs2num[ob] for ob in obs]
        
        ensN = exper['ne']
        t    = len(file_list)
        n = np.max([len(xr.open_dataset(file).ob_num) for file in file_list])
        times = [DT.datetime.strptime(os.path.basename(file).replace(file_version, ''), '_%Y-%m-%d_%H:%M:%S.nc') for file in file_list]
        
        # step one - make the skeleton of dataset
        coords = { 't': np.arange(0, t),'ne': np.arange(0,ensN),'n':  np.arange(0, n)}
        myds = xr.Dataset( coords)
        
        # fill with nan variables of proper size
        f = xr.open_dataset(file_list[0])
        for v in list(f.keys()):
            if v not in ['type', 'dates']:
                if len(np.shape(f[v])) == 1:
                    myds[v] = (('t', 'n'), np.zeros([t, n])*np.nan)
                if len(np.shape(f[v])) == 2:
                    myds[v] = (('t', 'n', 'ne'), np.zeros([t, n, ensN])*np.nan)
        f.close()
                    
        # fill nan variables with actual data
        for fi, file in enumerate(file_list):
            f = xr.open_dataset(file)
            fn = len(f.ob_num)
            for v in list(myds.keys()):
                myds[v][fi, :fn] = f[v].values
            f.close()
        
        # add time var
        myds['time'] =  (('t'), times) 
        
       # add masks for different variables
        fix_kinds = myds.kind.values
        fix_kinds[np.isnan(fix_kinds)] = -999
        myds['kind'] = (('t', 'n'), fix_kinds)
        for ob in obs:
            myds[ob] = (('t', 'n'), myds['kind'].values == obs2num[ob])
        
        ##### now add in the posterior values!!
        myds['Hxf_post']= (('t', 'n', 'ne'), np.zeros([t, n, ensN])*np.nan)
        myds['Hxfbar_post']= (('t', 'n'), np.zeros([t, n])*np.nan)
        myds['outlier_post']= (('t', 'n'), np.zeros([t, n])*np.nan)
        
        file_version='Posterior'
        dirname = os.path.join(path,file_version+'*.nc')
        file_list = sorted(glob.glob(dirname),key=os.path.getmtime)
        for fi, file in enumerate(file_list):
            f = xr.open_dataset(file)
            fn = len(f.ob_num)
            #for v in list(myds.keys()):
            myds['Hxf_post'][fi, :fn] = f['Hxf'].values
            myds['Hxfbar_post'][fi, :fn] = f['Hxfbar'].values
            myds['outlier_post'][fi, :fn] = f['outlier'].values
            f.close()
        
        savename = os.path.join(os.path.dirname(file_list[0]), f'AllPrior_Post.nc')
        myds.to_netcdf(savename, format='NETCDF4')


## make the forecast file

    if options.fcst:

        print('PRODUCING FORECAST FILES')

        if options.fcst_file: # from a forecast run only
            start_time = dt.datetime.strptime(exper['FORECAST']['start'], '%Y-%m-%d %H:%M:%S')
            end_time   = dt.datetime.strptime(exper['FORECAST']['end'], '%Y-%m-%d %H:%M:%S')
            timedel    = dt.timedelta(seconds = exper['FORECAST']['freq'])

        else: # from a typical experiment
            timedel    = dt.timedelta(seconds = exper['forecast_freq'])
            da_end     = dt.datetime.strptime(exper['DA_PARAMS']['DA_end_time'], '%Y-%m-%d %H:%M:%S') 
            start_time = da_end + timedel
            end_time   = da_end + dt.timedelta(seconds = exper['forecast_length']) 
    
        timearr = np.arange(start_time, end_time+timedel, timedel)
         
        
        for i, time in enumerate(timearr):
            time = time.astype(dt.datetime)
        
            files, myDT = ens.FindRestartFiles(exper, time, ret_exp=False, prior=False)
            ens_state = ens.read_CM1_ens(files, exper, state_vector=None, DateTime=myDT, addmean=1) # the final member is the mean member!!!!
            ens.ens_CM1_coords(ens_state)
        
            if i == 0:
                allvars = ens_state['state_vector']['xyz3d']
        
                nt,nk,nj,ni,ne = len(timearr), ens_state['nz'],ens_state['ny'],ens_state['nx'],ens_state['ne']+1
                
                coords = {'t'    : np.arange(0, nt),'ni'   : np.arange(0, ni),'nj'   : np.arange(0, nj),'nk'   : np.arange(0, nk), 'ne':np.arange(0,ne)}
                data_vars = { 'time': (['t'], [t.astype(dt.datetime) for t in timearr]), 
                              'xh': (['ni'], ens_state['xc'][:]/1000), 
                              'yh': (['nj'], ens_state['yc'][:]/1000),
                              'z' : (['nk'], ens_state['zc'][:]/1000)}
                
                for v in allvars:
                    data_vars[v.lower()] = (['t','ne','nk','nj','ni'], np.zeros([nt,ne,nk,nj,ni])*np.nan)
                myds = xr.Dataset(data_vars, coords)
        
            for v in allvars:
                myds[v.lower()][i,:,:,:,:] = ens_state[v][:]
        
            del ens_state

        # now add in 2-5 km UH
        z = myds.z
        ztop = findnearest(z, 5)
        zbot = findnearest(z, 2)
        
        # note = we are calculating this for the mean member as well
        w        = myds['w'][:, :, zbot:ztop+1].values
        u        = myds['u'][:, :, zbot:ztop+1].values
        v        = myds['v'][:, :, zbot:ztop+1].values
        
        dx  = np.gradient(myds.xh)*1000
        dy  = np.gradient(myds.yh)*1000
        dz  = np.gradient(myds.z)[zbot:ztop+1]*1000
        
        dudy = np.gradient(u, axis=3)/dy
        dvdx = np.gradient(v, axis=4)/dx
        zeta = dvdx-dudy
        
        UH = np.sum(zeta*w*dz[np.newaxis, np.newaxis, :, np.newaxis, np.newaxis], axis=2)
        del u,v,w,dx,dy,dz,dudy, dvdx, zeta
        
        myds['UH_2-5km'] = (('t', 'ne','nj','ni'), UH)
        
        myds.to_netcdf(exper['base_path']+'/full_ens_fcst.nc', format='NETCDF4')


# calculate WTD residual

    if options.wtg:

        fcst = exper['fcst_members']
        
        for i, f in enumerate(fcst):

            stats = xr.open_dataset(f'{f}/cm1out_stats.nc', decode_timedelta=False)
        
            if i == 0:
                time=stats.time.values.astype(int)/60.0
                members = np.arange(1, len(fcst)+1, 1)
        
                WRES = np.zeros([len(time), len(members)])
                QR   = np.zeros([len(time), len(members)])
                DPDT = np.zeros([len(time), len(members)])
                DIVC = np.zeros([len(time), len(members)])
        
            WRES[:, i] = stats.wresmean5000.values
            QR[:,i]    = stats.qrmean.values
            DPDT[:,i]  = stats.pptenmean.values/100
            DIVC[:,i]  = stats.divmean.values * (343**2)
            stats.close()
            
        coords = {'t'    : np.arange(0, len(time)), 'ne':np.arange(0,len(fcst))}
        
        data_vars = { 'time': (['t'], time), 
                      'wres': (['t', 'ne'], WRES), 
                      'qr'  : (['t', 'ne'], QR), 
                      'dpdt': (['t', 'ne'], DPDT),
                      'divc': (['t', 'ne'], DIVC) }
        
        myds = xr.Dataset(data_vars, coords)
        myds.to_netcdf(exper['base_path']+'/balance.nc', format='NETCDF4')

        # print('PRODUCING WEAK THERMAL GRADIENT ANALYSIS FILE')

        # members = np.arange(1,exper['ne']+1,1)
        # times = np.arange(0, len(glob.glob(exper['fcst_members'][0]+'/cm1rst*')), 1)
    
        # fpath = exper['base_path']
    
        # qr   = np.zeros([len(members), len(times)]) #n members, n timesteps
        # wres = np.zeros([len(members), len(times)]) #n members, n timesteps
        
        # mtime = []
        
        # for member in members:
        #     print(member, end=',')
        
        #     for i,t in enumerate(times):
            
        #         cm1 = xr.open_dataset(f'{fpath}/member{member:03d}/cm1rst_{t:06d}.nc', decode_timedelta=True)
        #         mtime.append(int(cm1.time[0]/1e9/60))
                
        #         # note - this is theta tendencies from the microphysics scheme
        #         qtten = cm1.qtten.values[0]
                
        #         # calc w
        #         wa = cm1.wa.values[0]
        #         nz = len(cm1.nk)
        #         w = np.zeros_like(qtten)*np.nan
        #         w[0,:,:]      = 0.5*(wa[0,:,:]    + wa[1,:,:])
        #         w[nz-1,:,:]   = 0.5*(wa[nz-1,:,:] + wa[nz,:,:])
        #         w[1:nz-1,:,:] = (wa[0:nz-2,:,:]   + 13.0*wa[1:nz-1,:,:] -wa[3:nz+1,:,:] + 13.0*wa[2:nz,:,:] ) / 24.0
                
        #         th0 = cm1.theta.values[0,:,:, -10:].mean(axis=(1,2))
        #         dz  = np.gradient(cm1.zh)
                
        #         dth0dz = np.gradient(th0, axis=0)/dz #K/m
    
        #         W_wtg = qtten/dth0dz[:, np.newaxis, np.newaxis]
        #         W_res = w - W_wtg # residual vertical velocity that is not balanced by heat sources 
                
        #         wres[member-1, i] = np.mean(np.abs(W_res[findnearest(cm1.zh, 5000)]))
        #         qr[member-1, i] = cm1.qr[:,:,:,:].mean()
        
        #         cm1.close()
    
        # coords = {
        #         't'    : np.arange(0, len(times)),
        #         'ne'   : np.arange(0, len(members)),}
        
        # data_vars = { 
        #     'time'                     : (['t'], np.unique(mtime)),
        #     'wres'                     : (['ne','t'], wres),
        #     'qr'                       : (['ne','t'], qr)}
        
        # myds = xr.Dataset(data_vars, coords)
        # myds.to_netcdf(exper['base_path']+'/WTG.nc', format='NETCDF4')
          